# Region sizes
xsmall: 5
small: 7
medium: 11
large: 15
xlarge: 21

# The prospecting tool
wand: 286

# Outline block
outline: 20

# MySQL info
mysql:
    host: localhost
    port: 3306
    database: minecraft
    user: root
    password: password
    prefix: ds_
