# Region sizes
sizes:
    xsmall: 5
    small: 7
    medium: 11
    large: 15
    xlarge: 21
    
# Maximum volume a player can claim
volumes: 
    xsmall: 125
    small: 343
    medium: 1331
    large: 11390625
    xlarge: 85766121

# The prospecting tool
wand: 286

# Outline block
outline: 20
