# Region sizes
xsmall: 5
small: 7
medium: 11
large: 15
xlarge: 21

# The prospecting tool
wand: 286

# Outline block
outline: 20
cache: 200

# MySQL info HOST IS ALWAYS LOCALHOST
mysql:
    port: 3306
    database: minecraft
    user: minecraft
    password: minecraft
